/** @file core_components.c
 * Contains the static definition of the function block reference table for EHS
 *
 * @author: inx limited
 * @version: $Revision: 5462 $
 * @date: $Date: 2006-10-30 05:05:44 +0000 (Mon, 30 Oct 2006), $
 *
 * Copyright (c), inx limited, 2007. All rights reserved.
 */


#include "blockref_table.h"
#include "hal.h" /* Required for logging */
#include "fid.h"  /* for the Function Instance data types */

/* Components */
#include "arraystring1.h"
#include "buffer.h"
#include "calc_i.h"
#include "const1.h"
#include "convertor.h"
#include "demux.h"
#include "event_counter1.h"
#include "file.h"
#include "ehs_if.h"
#include "logic.h"
#include "mux.h"
#include "operator1.h"
#include "sfc.h"
#include "state.h"
#include "stringfn.h"
#include "time_clock.h"
#include "wall_clock.h"
#include "trigger.h"
#include "fs_dir_list1.h"
#include "fs_dir_create_remove.h"
#include "system_exec.h"

#include "rtinfo.h"
#include "appinfo.h"
#include "appget.h"



const EhsBlockRefType EhsBlockRefTable_core[] =
{
#ifdef EHS_TARGET_FP_SUPPORT
	/* from buffer.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_FIFOREAL_NAME, FIFOReal),
	EHS_BLOCKREF_ENTRY(EHS_FB_LIFOREAL_NAME, LIFOReal),
	/* from const.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_CONSTANT_FLOAT_NAME, ConstantFloat1),
	/* convertor.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_FLOAT_TO_BOOL_NAME, ConvertorRealToBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_FLOAT_TO_INT_NAME, ConvertorRealToInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_FLOAT_TO_STRING_NAME, ConvertorRealToString),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_BOOL_TO_FLOAT_NAME, ConvertorBoolToReal),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_INT_TO_FLOAT_NAME, ConvertorIntToReal),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_STRING_TO_FLOAT_NAME, ConvertorStringToReal),
	/* demux.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_TWO_OUTPUT_FLOAT_NAME, DemultiplexTwoOutputFloat),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_THREE_OUTPUT_FLOAT_NAME, DemultiplexThreeOutputFloat),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_FOUR_OUTPUT_FLOAT_NAME, DemultiplexFourOutputFloat),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_INDEXED_DEMULTIPLEX_FLOAT_NAME,IndexedDemultiplexer_Float, EHS_FB_INIT_NAME(IndexedDemultiplexer),EHS_FB_IDENTIFY_NAME(IndexedDemultiplexer)),
	/* file.h */
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILE_READONLY_FLOAT_NAME, FILE_ReadOnly_Float),
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILE_WRITEONLY_FLOAT_NAME, FILE_WriteOnly_Float),
	/* multiplexerFunctions.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_TWO_INPUT_FLOAT_NAME, MultiplexTwoInputFloat),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_THREE_INPUT_FLOAT_NAME, MultiplexThreeInputFloat),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_FOUR_INPUT_FLOAT_NAME, MultiplexFourInputFloat),
	/* operator1.h */
	EHS_BLOCKREF_ENTRY(EHS_ADDITION_TWO_INPUT_REAL_NAME, AdditionTwoInputReal),
	EHS_BLOCKREF_ENTRY(EHS_ADDITION_THREE_INPUT_FLOAT_NAME, AdditionThreeInputReal),
	EHS_BLOCKREF_ENTRY(EHS_ADDITION_FOUR_INPUT_FLOAT_NAME, AdditionFourInputReal),
	EHS_BLOCKREF_ENTRY(EHS_SUBTRACTION_FLOAT_NAME, SubtractionReal),
	EHS_BLOCKREF_ENTRY(EHS_MULTIPLY_TWO_INPUT_FLOAT_NAME, MultiplyTwoInputReal),
	EHS_BLOCKREF_ENTRY(EHS_MULTIPLY_THREE_INPUT_FLOAT_NAME, MultiplyThreeInputReal),
	EHS_BLOCKREF_ENTRY(EHS_MULTIPLY_FOUR_INPUT_FLOAT_NAME, MultiplyFourInputReal),
	EHS_BLOCKREF_ENTRY(EHS_DIVISION_FLOAT_NAME, DivisionReal),
	EHS_BLOCKREF_ENTRY(EHS_MODULUS_FLOAT_NAME, ModulusReal),
	EHS_BLOCKREF_ENTRY(EHS_POWER_FLOAT_NAME, PowerReal),
	EHS_BLOCKREF_ENTRY(EHS_SQUARE_FLOAT_NAME, SquareReal),
	EHS_BLOCKREF_ENTRY(EHS_ADD_ACCUMULATE_FLOAT_NAME, AddAccumulateReal),
	EHS_BLOCKREF_ENTRY(EHS_SQUARE_ROOT_FLOAT_NAME, SquareRootReal),
	EHS_BLOCKREF_ENTRY(EHS_LOG_BASE_TEN_FLOAT_NAME, LogBaseTenReal),
	EHS_BLOCKREF_ENTRY(EHS_LOG_FLOAT_NAME, LogReal),
	EHS_BLOCKREF_ENTRY(EHS_SINE_FLOAT_NAME, SineReal),
	EHS_BLOCKREF_ENTRY(EHS_COSINE_FLOAT_NAME, CosineReal),
	EHS_BLOCKREF_ENTRY(EHS_TAN_FLOAT_NAME, TanReal),
	EHS_BLOCKREF_ENTRY(EHS_ARC_SINE_FLOAT_NAME, ArcSineReal),
	EHS_BLOCKREF_ENTRY(EHS_ARC_COSINE_FLOAT_NAME, ArcCosineReal),
	EHS_BLOCKREF_ENTRY(EHS_ARC_TAN_FLOAT_NAME, ArcTanReal),
	EHS_BLOCKREF_ENTRY(EHS_HYPERBOLIC_SINE_FLOAT_NAME, HyperbolicSineReal),
	EHS_BLOCKREF_ENTRY(EHS_HYPERBOLIC_COSINE_FLOAT_NAME, HyperbolicCosineReal),
	EHS_BLOCKREF_ENTRY(EHS_HYPERBOLIC_TAN_FLOAT_NAME, HyperbolicTanReal),
	EHS_BLOCKREF_ENTRY(EHS_ARC_HYPERBOLIC_SINE_FLOAT_NAME, ArcHyperbolicSineReal),
	EHS_BLOCKREF_ENTRY(EHS_ARC_HYPERBOLIC_COSINE_FLOAT_NAME, ArcHyperbolicCosineReal),
	EHS_BLOCKREF_ENTRY(EHS_ARC_HYPERBOLIC_TAN_FLOAT_NAME, ArcHyperbolicTanReal),
	EHS_BLOCKREF_ENTRY(EHS_COMPARATOR_GREATER_FLOAT_NAME, ComparatorGreaterReal1),
	EHS_BLOCKREF_ENTRY(EHS_COMPARATOR_GREATER_EQUAL_FLOAT_NAME, ComparatorGreaterEqualReal1),
	EHS_BLOCKREF_ENTRY(EHS_COMPARATOR_EQUAL_FLOAT_NAME, ComparatorEqualReal1),
	EHS_BLOCKREF_ENTRY(EHS_INTEGRATOR_FLOAT_NAME, IntegratorReal),
	EHS_BLOCKREF_ENTRY(EHS_EXPONENTIAL_FLOAT_NAME, ExponentialReal),
	EHS_BLOCKREF_ENTRY(EHS_FB_ARRAYREAL_NAME,ArrayReal1),

#endif /* EHS_TARGET_FP_SUPPORT */

	/* from arraystring1.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_ARRAYSTRING_NAME,ArrayString1),
	EHS_BLOCKREF_ENTRY(EHS_FB_ARRAYINT_NAME,ArrayInt1),
	EHS_BLOCKREF_ENTRY(EHS_FB_ARRAYBOOL_NAME,ArrayBool1),
	/* from bufferFunctions.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_FIFOINT_NAME, FIFOInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_LIFOINT_NAME, LIFOInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_FIFOBOOL_NAME, FIFOBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_LIFOBOOL_NAME, LIFOBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_FIFOSTRING_NAME, FIFOString),
	EHS_BLOCKREF_ENTRY(EHS_FB_LIFOSTRING_NAME, LIFOString),
	/* calc_i.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_CALC_1_INT_NAME,ICalc_1),
	EHS_BLOCKREF_ENTRY(EHS_FB_CALC_2_INT_NAME,ICalc_2),
	EHS_BLOCKREF_ENTRY(EHS_FB_CALC_4_INT_NAME,ICalc_4),
	EHS_BLOCKREF_ENTRY(EHS_FB_CALC_6_INT_NAME,ICalc_6),
	EHS_BLOCKREF_ENTRY(EHS_FB_CALC_8_INT_NAME,ICalc_8),
	/* from constFunctions.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_CONSTANT_INT_NAME, ConstantInt1),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONSTANT_STRING_NAME, ConstantString1),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONSTANT_BOOL_NAME, ConstantBool1),
	/* convertorFunctions.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_BOOL_TO_TRIGGER_NAME, ConvertorBoolToTrigger),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_BOOL_TO_INT_NAME, ConvertorBoolToInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_BOOL_TO_STRING_NAME, ConvertorBoolToString),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_INT_TO_BOOL_NAME, ConvertorIntToBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_INT_TO_STRING_NAME, ConvertorIntToString),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_STRING_TO_BOOL_NAME, ConvertorStringToBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_CONVERTOR_STRING_TO_INT_NAME, ConvertorStringToInt),
	/* demux.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_TWO_OUTPUT_INT_NAME, DemultiplexTwoOutputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_THREE_OUTPUT_INT_NAME, DemultiplexThreeOutputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_FOUR_OUTPUT_INT_NAME, DemultiplexFourOutputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_TWO_OUTPUT_BOOL_NAME, DemultiplexTwoOutputBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_THREE_OUTPUT_BOOL_NAME, DemultiplexThreeOutputBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_FOUR_OUTPUT_BOOL_NAME, DemultiplexFourOutputBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_TWO_OUTPUT_STRING_NAME, DemultiplexTwoOutputString),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_THREE_OUTPUT_STRING_NAME, DemultiplexThreeOutputString),
	EHS_BLOCKREF_ENTRY(EHS_FB_DEMULTIPLEX_FOUR_OUTPUT_STRING_NAME, DemultiplexFourOutputString),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_INDEXED_DEMULTIPLEX_BOOL_NAME,IndexedDemultiplexer_Bool,EHS_FB_INIT_NAME(IndexedDemultiplexer),EHS_FB_IDENTIFY_NAME(IndexedDemultiplexer)),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_INDEXED_DEMULTIPLEX_INT_NAME,IndexedDemultiplexer_Int,EHS_FB_INIT_NAME(IndexedDemultiplexer),EHS_FB_IDENTIFY_NAME(IndexedDemultiplexer)),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_INDEXED_DEMULTIPLEX_STRING_NAME,IndexedDemultiplexer_String,EHS_FB_INIT_NAME(IndexedDemultiplexer),EHS_FB_IDENTIFY_NAME(IndexedDemultiplexer)),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_INDEXED_DEMULTIPLEX_EVENT_NAME,IndexedDemultiplexer_Event,EHS_FB_INIT_NAME(IndexedDemultiplexer),EHS_FB_IDENTIFY_NAME(IndexedDemultiplexer)),
	EHS_BLOCKREF_ENTRY(EHS_FB_TEXTCASE_DEMULTIPLEX_EVENT_NAME, TextCaseDemultiplexer_Event),
	/* eventCounter1.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_EVENT_COUNTER_VERSATILE1_NAME,EventCounterVersatile1),
	/* fileFunctions.h */
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILE_READONLY_INT_NAME, FILE_ReadOnly_Int),
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILE_WRITEONLY_INT_NAME, FILE_WriteOnly_Int),
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILE_READONLY_BOOL_NAME, FILE_ReadOnly_Bool),
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILE_WRITEONLY_BOOL_NAME, FILE_WriteOnly_Bool),
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILE_READONLY_STRING_NAME, FILE_ReadOnly_String),
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILE_WRITEONLY_STRING_NAME, FILE_WriteOnly_String),
	/* ehs_if.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_IF_NAME,If),
	/* logic.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_NOT_NAME, LogicNot),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_2INPUT_AND_NAME, LogicTwoInputAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_3INPUT_AND_NAME, LogicThreeInputAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_4INPUT_AND_NAME, LogicFourInputAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_2INPUT_OR_NAME, LogicTwoInputOr),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_3INPUT_OR_NAME, LogicThreeInputOr),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_4INPUT_OR_NAME, LogicFourInputOr),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_2INPUT_NOR_NAME, LogicTwoInputNor),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_3INPUT_NOR_NAME, LogicThreeInputNor),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_4INPUT_NOR_NAME, LogicFourInputNor),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_2INPUT_NAND_NAME, LogicTwoInputNand),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_3INPUT_NAND_NAME, LogicThreeInputNand),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_4INPUT_NAND_NAME, LogicFourInputNand),
	EHS_BLOCKREF_ENTRY(EHS_FB_LOGIC_XOR_NAME, LogicXor),
	/* mux.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_TWO_INPUT_INT_NAME, MultiplexTwoInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_THREE_INPUT_INT_NAME, MultiplexThreeInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_FOUR_INPUT_INT_NAME, MultiplexFourInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_TWO_INPUT_BOOL_NAME, MultiplexTwoInputBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_THREE_INPUT_BOOL_NAME, MultiplexThreeInputBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_FOUR_INPUT_BOOL_NAME, MultiplexFourInputBool),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_TWO_INPUT_STRING_NAME, MultiplexTwoInputString),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_THREE_INPUT_STRING_NAME, MultiplexThreeInputString),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLEX_FOUR_INPUT_STRING_NAME, MultiplexFourInputString),
	EHS_BLOCKREF_ENTRY(EHS_FB_INDEXED_MULTIPLEXER_EVENT_NAME, IndexedMultiplexer_Event),
	/* operator1.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_ADDITION_TWO_INPUT_INT_NAME, AdditionTwoInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_ADDITION_THREE_INPUT_INT_NAME, AdditionThreeInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_ADDITION_FOUR_INPUT_INT_NAME, AdditionFourInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_SUBTRACTION_INT_NAME, SubtractionInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLY_TWO_INPUT_INT_NAME, MultiplyTwoInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLY_THREE_INPUT_INT_NAME, MultiplyThreeInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_MULTIPLY_FOUR_INPUT_INT_NAME, MultiplyFourInputInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_DIVISION_INT_NAME, DivisionInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_MODULUS_INT_NAME, ModulusInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_POWER_INT_NAME, PowerInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_SQUARE_INT_NAME, SquareInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_ADD_ACCUMULATE_INT_NAME, AddAccumulateInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_SUB_ACCUMULATE_INT_NAME, SubAccumulateInt),
	EHS_BLOCKREF_ENTRY(EHS_FB_ABS_INT_NAME, AbsInt),
	EHS_BLOCKREF_ENTRY(EHS_COMPARATOR_GREATER_INT_NAME, ComparatorGreaterInt1),
	EHS_BLOCKREF_ENTRY(EHS_COMPARATOR_GREATER_EQUAL_INT_NAME, ComparatorGreaterEqualInt1),
	EHS_BLOCKREF_ENTRY(EHS_COMPARATOR_EQUAL_INT_NAME, ComparatorEqualInt1),
	EHS_BLOCKREF_ENTRY(EHS_INTEGRATOR_INT_NAME, IntegratorInt),
	EHS_BLOCKREF_ENTRY(EHS_MAXINT_INT_NAME, MaxInt),
	EHS_BLOCKREF_ENTRY(EHS_MININT_INT_NAME, MinInt),
	/* sfc.h */
	EHS_BLOCKREF_ENTRY(EHS_SFC_NAME, SFCBar),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP1_NAME, SFCBarGroup1),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP2_NAME, SFCBarGroup2),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP3_NAME, SFCBarGroup3),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP4_NAME, SFCBarGroup4),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP8_NAME, SFCBarGroup8),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP12_NAME, SFCBarGroup12),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP1EVENT_NAME, SFCBarGroup1Event),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP2EVENT_NAME, SFCBarGroup2Event),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP3EVENT_NAME, SFCBarGroup3Event),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP4EVENT_NAME, SFCBarGroup4Event),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP8EVENT_NAME, SFCBarGroup8Event),
	EHS_BLOCKREF_ENTRY(EHS_SFC_BAR_GROUP12EVENT_NAME, SFCBarGroup12Event),
	/* state.h */
	EHS_BLOCKREF_ENTRY(EHS_STATE_NAME, state),
	/* stringfn.h */
	EHS_BLOCKREF_ENTRY(EHS_CAT_STRING_NAME, string_cat),
	EHS_BLOCKREF_ENTRY(EHS_CMP_STRING_NAME, string_cmp),
	EHS_BLOCKREF_ENTRY_EX(EHS_LEN_STRING_NAME, string_len,NULL,NULL),
	EHS_BLOCKREF_ENTRY(EHS_STRING_FORMAT_NAME, string_format),
	EHS_BLOCKREF_ENTRY(EHS_STRING_FORMAT_NAME8, string_format8),
	EHS_BLOCKREF_ENTRY(EHS_STRING_SCANF8_NAME, stringfn_scanf8),
	EHS_BLOCKREF_ENTRY(EHS_FIND_STRING_NAME, string_find),
	EHS_BLOCKREF_ENTRY_EX(EHS_TO_UPPER_STRING_NAME, string_toUpper,NULL,NULL),
	EHS_BLOCKREF_ENTRY_EX(EHS_TO_LOWER_STRING_NAME, string_toLower,NULL,NULL),
	EHS_BLOCKREF_ENTRY_EX(EHS_CHAR_AT_STRING_NAME, string_charAt,NULL,NULL),
	EHS_BLOCKREF_ENTRY_EX(EHS_STR_AT_STRING_NAME, string_strAt,NULL,NULL),
	EHS_BLOCKREF_ENTRY(EHS_INSERT_STRING_NAME, string_insert),
	EHS_BLOCKREF_ENTRY(EHS_SUBSTRING_NAME, string_sub),
	/* time_clock.h */
	EHS_BLOCKREF_ENTRY(EHS_TIME_CLOCK_NAME, time_clock),
	/* trigger.h */
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_START_NAME, Start, NULL, NULL),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_EVENT_BOOLEAN_CONTROL_NAME, EventBooleanControl, NULL, NULL),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_TWO_INPUT_LATCHING_AND_NAME, EventTwoInputLatchingAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_THREE_INPUT_LATCHING_AND_NAME, EventThreeInputLatchingAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_FOUR_INPUT_LATCHING_AND_NAME, EventFourInputLatchingAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_ONE_INPUT_MANUAL_RESET_AND_NAME, EventOneInputManRstAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_TWO_INPUT_MANUAL_RESET_AND_NAME, EventTwoInputManRstAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_THREE_INPUT_MANUAL_RESET_AND_NAME, EventThreeInputManRstAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_FOUR_INPUT_MANUAL_RESET_AND_NAME, EventFourInputManRstAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_SELF_RESET_TWO_INPUT_LATCHING_AND_NAME, EventSelfResetTwoInputLatchingAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_SELF_RESET_THREE_INPUT_LATCHING_AND_NAME, EventSelfResetThreeInputLatchingAnd),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_SELF_RESET_FOUR_INPUT_LATCHING_AND_NAME, EventSelfResetFourInputLatchingAnd),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_TRIGGER_TWO_INPUT_OR_NAME, EventTwoInputOr, NULL, NULL),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_TRIGGER_THREE_INPUT_OR_NAME, EventThreeInputOr, NULL, NULL),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_TRIGGER_FOUR_INPUT_OR_NAME, EventFourInputOr, NULL, NULL),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_TOGGLE_BOOLEAN_NAME, EventToggleBoolean),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_POSITIVE_EDGE_DETECT_NAME, EventPositiveEdgeDetect),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_NEGATIVE_EDGE_DETECT_NAME, EventNegativeEdgeDetect),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_EDGE_DETECT_NAME, EventEdgeDetect),
	EHS_BLOCKREF_ENTRY_EX(EHS_FB_TRIGGER_SET_RESET_NAME, EventSetReset, NULL, NULL),
	EHS_BLOCKREF_ENTRY(EHS_FB_TRIGGER_COUNTER_NAME, EventCounter),
	EHS_BLOCKREF_ENTRY("RuntimeInfo", runtimeinfo),
	EHS_BLOCKREF_ENTRY("AppInfo", appinfo),
	EHS_BLOCKREF_ENTRY("wall_clock", wall_clock),
	EHS_BLOCKREF_ENTRY_WITH_DESTROY(EHS_FB_FILESYSTEM_DIRLIST_NAME, FileSystemDirList1),
	EHS_BLOCKREF_ENTRY(EHS_FB_FILESYSTEM_DIRCREATEREMOVE_NAME, FileSystemDirCreateRemove),
	/* system_exec.h */
	EHS_BLOCKREF_ENTRY(EHS_FB_EXEC_NAME, Exec),
	#ifdef EHS_DEVMAN_SUPPORT
		EHS_BLOCKREF_ENTRY("AppGet", appget),
	#endif

	{0}
};

