<?xml version="1.0" encoding="UTF-8"?><Component>
    <Module>usercomponents</Module>
    <CDFInfo>
        <Version>3</Version>
        <CreationDate>2024-10-16T09:18:41Z</CreationDate>
        <UpdatedDate>2024-10-16T09:22:59Z</UpdatedDate>
    </CDFInfo>
    <Description>
        <ShortDescription>Parse the string value from json string input or file.</ShortDescription>
        <LongDescription>Parse the string value from json string input or file.</LongDescription>
        <UserName/>
        <Menu>
            Data Utilities
            <Menu>
                JSON
                <Menu>
                    Key Value
                    <Menu>string</Menu>
                </Menu>
            </Menu>
        </Menu>
    </Description>
    <Block>
        <Type>Data</Type>
        <Height>215</Height>
        <Text>JSON</Text>
        <TextX>8</TextX>
        <TextY>5</TextY>
        <TextScale>1.25</TextScale>
        <TextVertical>0</TextVertical>
        <LocationX>0</LocationX>
        <LocationY>-15</LocationY>
    </Block>
    <FBID>
        <ERT1_ID>1</ERT1_ID>
        <Class>json_parser_str</Class>
    </FBID>
    <Hashes>
        <NameHash_CRC16>0xE643</NameHash_CRC16>
        <FbApiDescriptorHash_CRC32>5ee55e8b</FbApiDescriptorHash_CRC32>
        <FbApiDescriptorHash/>
    </Hashes>
    <Parameters>
        <Parameter>
            <Name>file</Name>
            <DataType>S</DataType>
            <DefaultValue>default.js</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>JSON filename. Will be ignored if there is the string input.</Description>
            <ListPlacement>1</ListPlacement>
            <ArgPlacement>1</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k1</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 1</Description>
            <ListPlacement>2</ListPlacement>
            <ArgPlacement>2</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k2</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 2</Description>
            <ListPlacement>3</ListPlacement>
            <ArgPlacement>3</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k3</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 3</Description>
            <ListPlacement>4</ListPlacement>
            <ArgPlacement>4</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k4</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 4</Description>
            <ListPlacement>5</ListPlacement>
            <ArgPlacement>5</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k5</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 5</Description>
            <ListPlacement>6</ListPlacement>
            <ArgPlacement>6</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k6</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 6</Description>
            <ListPlacement>7</ListPlacement>
            <ArgPlacement>7</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k7</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 7</Description>
            <ListPlacement>8</ListPlacement>
            <ArgPlacement>8</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k8</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 8</Description>
            <ListPlacement>9</ListPlacement>
            <ArgPlacement>9</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k9</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 9</Description>
            <ListPlacement>10</ListPlacement>
            <ArgPlacement>10</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k10</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 10</Description>
            <ListPlacement>11</ListPlacement>
            <ArgPlacement>11</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k11</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 11</Description>
            <ListPlacement>12</ListPlacement>
            <ArgPlacement>12</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k12</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 12</Description>
            <ListPlacement>13</ListPlacement>
            <ArgPlacement>13</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k13</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 13</Description>
            <ListPlacement>14</ListPlacement>
            <ArgPlacement>14</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k14</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 14</Description>
            <ListPlacement>15</ListPlacement>
            <ArgPlacement>15</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k15</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 15</Description>
            <ListPlacement>16</ListPlacement>
            <ArgPlacement>16</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>k16</Name>
            <DataType>S</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>key 16</Description>
            <ListPlacement>17</ListPlacement>
            <ArgPlacement>17</ArgPlacement>
        </Parameter>
    </Parameters>
    <Functions>
        <Function>
            <name>parse</name>
            <ID>
                <ERT1_ID>1</ERT1_ID>
            </ID>
        </Function>
    </Functions>
    <Ports>
        <Port>
            <Description/>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>12</YCoordinate>
            <CName>parse</CName>
            <Function argument="0">
                <Function_ERT1_ID>1</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description/>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>22</YCoordinate>
            <CName>input_str</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k1</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>42</YCoordinate>
            <CName>key1</CName>
            <Function argument="2">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k2</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>52</YCoordinate>
            <CName>key2</CName>
            <Function argument="3">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k3</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>62</YCoordinate>
            <CName>key3</CName>
            <Function argument="4">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k4</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>72</YCoordinate>
            <CName>key4</CName>
            <Function argument="5">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k5</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>82</YCoordinate>
            <CName>key5</CName>
            <Function argument="6">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k6</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>92</YCoordinate>
            <CName>key6</CName>
            <Function argument="7">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k7</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>102</YCoordinate>
            <CName>key7</CName>
            <Function argument="8">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k8</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>112</YCoordinate>
            <CName>key8</CName>
            <Function argument="9">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k9</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>122</YCoordinate>
            <CName>key9</CName>
            <Function argument="10">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k10</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>132</YCoordinate>
            <CName>key10</CName>
            <Function argument="11">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k11</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>142</YCoordinate>
            <CName>key11</CName>
            <Function argument="12">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k12</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>152</YCoordinate>
            <CName>key12</CName>
            <Function argument="13">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k13</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>162</YCoordinate>
            <CName>key13</CName>
            <Function argument="14">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k14</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>172</YCoordinate>
            <CName>key14</CName>
            <Function argument="15">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k15</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>182</YCoordinate>
            <CName>key15</CName>
            <Function argument="16">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>k16</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>192</YCoordinate>
            <CName>key16</CName>
            <Function argument="17">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description/>
            <PortType>FinishPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>12</YCoordinate>
            <Wcet>0</Wcet>
            <CName>done</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>err</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>22</YCoordinate>
            <Wcet>0</Wcet>
            <CName>error</CName>
            <Function argument="2">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>errno</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>32</YCoordinate>
            <CName>err_no</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o1</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>42</YCoordinate>
            <CName>output1</CName>
            <Function argument="2">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o2</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>52</YCoordinate>
            <CName>output2</CName>
            <Function argument="3">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o3</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>62</YCoordinate>
            <CName>output3</CName>
            <Function argument="4">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o4</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>72</YCoordinate>
            <CName>output4</CName>
            <Function argument="5">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o5</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>82</YCoordinate>
            <CName>output5</CName>
            <Function argument="6">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o6</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>92</YCoordinate>
            <CName>output6</CName>
            <Function argument="7">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o7</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>102</YCoordinate>
            <CName>output7</CName>
            <Function argument="8">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o8</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>112</YCoordinate>
            <CName>output8</CName>
            <Function argument="9">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o9</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>122</YCoordinate>
            <CName>output9</CName>
            <Function argument="10">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o10</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>132</YCoordinate>
            <CName>output10</CName>
            <Function argument="11">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o11</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>142</YCoordinate>
            <CName>output11</CName>
            <Function argument="12">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o12</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>152</YCoordinate>
            <CName>output12</CName>
            <Function argument="13">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o13</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>162</YCoordinate>
            <CName>output13</CName>
            <Function argument="14">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o14</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>172</YCoordinate>
            <CName>output14</CName>
            <Function argument="15">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o15</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>182</YCoordinate>
            <CName>output15</CName>
            <Function argument="16">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>o16</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>45</XCoordinate>
            <YCoordinate>192</YCoordinate>
            <CName>output16</CName>
            <Function argument="17">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
    </Ports>
</Component>
