<?xml version="1.0" encoding="UTF-8"?><Component>
    <Module>usercomponents</Module>
    <CDFInfo>
        <Version>3</Version>
        <CreationDate>2023-04-26T13:19:55Z</CreationDate>
        <UpdatedDate>2023-04-26T13:24:40Z</UpdatedDate>
    </CDFInfo>
    <Description>
        <ShortDescription/>
        <LongDescription/>
        <UserName/>
        <Menu>
            Software Structure
            <Menu>
                State Machine
                <Menu>State Condition</Menu>
            </Menu>
        </Menu>
    </Description>
    <Block>
        <Type>State_Condition</Type>
        <Width>30</Width>
        <Height>30</Height>
    </Block>
    <FBID>
        <ERT1_ID>1</ERT1_ID>
        <Class>state_condition</Class>
    </FBID>
    <Hashes>
        <NameHash_CRC16>0xFDEE</NameHash_CRC16>
        <FbApiDescriptorHash_CRC32>a456f5fd</FbApiDescriptorHash_CRC32>
        <FbApiDescriptorHash/>
    </Hashes>
    <Parameters>
        <Parameter>
            <Name>__stateId</Name>
            <DataType>I</DataType>
            <DefaultValue>-1</DefaultValue>
            <MinValue>-2147483648</MinValue>
            <MaxValue>2147483647</MaxValue>
            <Description/>
            <ListPlacement>1</ListPlacement>
            <ArgPlacement>1</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>__nextStateId</Name>
            <DataType>I</DataType>
            <DefaultValue>-1</DefaultValue>
            <MinValue>-2147483648</MinValue>
            <MaxValue>2147483647</MaxValue>
            <Description/>
            <ListPlacement>2</ListPlacement>
            <ArgPlacement>2</ArgPlacement>
        </Parameter>
    </Parameters>
    <Functions>
        <Function>
            <name>doCondition</name>
            <ID>
                <ERT1_ID>1</ERT1_ID>
            </ID>
        </Function>
    </Functions>
    <Ports>
        <Port>
            <Description/>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>15</YCoordinate>
            <CName/>
            <Function argument="0">
                <Function_ERT1_ID>1</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>U</DataType>
            <Description/>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>0</YCoordinate>
            <CName/>
            <UserPort>
                <Type>StateMachine</Type>
            </UserPort>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description/>
            <PortType>FinishPort</PortType>
            <XCoordinate>25</XCoordinate>
            <YCoordinate>15</YCoordinate>
            <Wcet>0</Wcet>
            <CName/>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
    </Ports>
</Component>
