<?xml version="1.0" encoding="UTF-8"?><Component>
    <Module>usercomponents</Module>
    <CDFInfo>
        <Version>3</Version>
        <CreationDate>2025-12-22T00:00:00Z</CreationDate>
        <UpdatedDate>2026-01-16T09:57:41Z</UpdatedDate>
    </CDFInfo>
    <Description>
        <ShortDescription>BLE Service Manager</ShortDescription>
        <LongDescription>Creates and manages a Bluetooth Low Energy (BLE) GATT service with configurable characteristics. Supports up to 16 characteristics with read, write, notify, and indicate properties. Handles client connections, characteristic access, and notifications. Suitable for creating custom BLE peripherals on embedded devices.</LongDescription>
        <UserName/>
        <Menu>
            Networking
            <Menu>Bluetooth</Menu>
        </Menu>
    </Description>
    <Block>
        <Type>Data_Processor</Type>
        <Width>120</Width>
        <Height>200</Height>
        <Text>BLE Service</Text>
        <TextX>20</TextX>
        <TextY>5</TextY>
        <TextScale>1.0</TextScale>
        <TextVertical>0</TextVertical>
        <LocationX>0</LocationX>
        <LocationY>0</LocationY>
    </Block>
    <FBID>
        <ERT1_ID>1</ERT1_ID>
        <Class>ble_service</Class>
    </FBID>
    <Hashes>
        <NameHash_CRC16>0xA0B5</NameHash_CRC16>
        <FbApiDescriptorHash_CRC32>b4249593</FbApiDescriptorHash_CRC32>
        <FbApiDescriptorHash/>
    </Hashes>
    <Parameters>
        <Parameter>
            <Name>service_uuid</Name>
            <DataType>S</DataType>
            <DefaultValue>0000180A-0000-1000-8000-00805F9B34FB</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>128-bit UUID for the BLE service (format: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX) or 16-bit UUID (format: 0xXXXX)</Description>
            <ListPlacement>1</ListPlacement>
            <ArgPlacement>1</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>service_name</Name>
            <DataType>S</DataType>
            <DefaultValue>Custom Service</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>Human-readable name for the service</Description>
            <ListPlacement>2</ListPlacement>
            <ArgPlacement>2</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>num_chars</Name>
            <DataType>I</DataType>
            <DefaultValue>4</DefaultValue>
            <MinValue>1</MinValue>
            <MaxValue>16</MaxValue>
            <Description>Number of characteristics in this service (1-16)</Description>
            <ListPlacement>3</ListPlacement>
            <ArgPlacement>3</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>adv_interval_ms</Name>
            <DataType>I</DataType>
            <DefaultValue>100</DefaultValue>
            <MinValue>20</MinValue>
            <MaxValue>10240</MaxValue>
            <Description>Advertising interval in milliseconds (20-10240ms). Standard: 100ms for fast, 1000ms for slow.</Description>
            <ListPlacement>4</ListPlacement>
            <ArgPlacement>4</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>mtu_size</Name>
            <DataType>I</DataType>
            <DefaultValue>23</DefaultValue>
            <MinValue>23</MinValue>
            <MaxValue>512</MaxValue>
            <Description>Maximum Transmission Unit size in bytes (23-512). Default is 23 (BLE minimum).</Description>
            <ListPlacement>5</ListPlacement>
            <ArgPlacement>5</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_0_uuid</Name>
            <DataType>S</DataType>
            <DefaultValue>00002A00-0000-1000-8000-00805F9B34FB</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>UUID for characteristic 0</Description>
            <ListPlacement>6</ListPlacement>
            <ArgPlacement>6</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_0_name</Name>
            <DataType>S</DataType>
            <DefaultValue>Char 0</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>Name for characteristic 0</Description>
            <ListPlacement>7</ListPlacement>
            <ArgPlacement>7</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_0_props</Name>
            <DataType>I</DataType>
            <DefaultValue>3</DefaultValue>
            <MinValue>0</MinValue>
            <MaxValue>15</MaxValue>
            <Description>Properties for char 0: 1=Read, 2=Write, 4=Notify, 8=Indicate (combine with +)</Description>
            <ListPlacement>8</ListPlacement>
            <ArgPlacement>8</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_0_max_len</Name>
            <DataType>I</DataType>
            <DefaultValue>20</DefaultValue>
            <MinValue>1</MinValue>
            <MaxValue>512</MaxValue>
            <Description>Maximum data length for characteristic 0</Description>
            <ListPlacement>9</ListPlacement>
            <ArgPlacement>9</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_1_uuid</Name>
            <DataType>S</DataType>
            <DefaultValue>00002A01-0000-1000-8000-00805F9B34FB</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>UUID for characteristic 1</Description>
            <ListPlacement>10</ListPlacement>
            <ArgPlacement>10</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_1_name</Name>
            <DataType>S</DataType>
            <DefaultValue>Char 1</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>Name for characteristic 1</Description>
            <ListPlacement>11</ListPlacement>
            <ArgPlacement>11</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_1_props</Name>
            <DataType>I</DataType>
            <DefaultValue>3</DefaultValue>
            <MinValue>0</MinValue>
            <MaxValue>15</MaxValue>
            <Description>Properties for char 1: 1=Read, 2=Write, 4=Notify, 8=Indicate (combine with +)</Description>
            <ListPlacement>12</ListPlacement>
            <ArgPlacement>12</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_1_max_len</Name>
            <DataType>I</DataType>
            <DefaultValue>20</DefaultValue>
            <MinValue>1</MinValue>
            <MaxValue>512</MaxValue>
            <Description>Maximum data length for characteristic 1</Description>
            <ListPlacement>13</ListPlacement>
            <ArgPlacement>13</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_2_uuid</Name>
            <DataType>S</DataType>
            <DefaultValue>00002A02-0000-1000-8000-00805F9B34FB</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>UUID for characteristic 2</Description>
            <ListPlacement>14</ListPlacement>
            <ArgPlacement>14</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_2_name</Name>
            <DataType>S</DataType>
            <DefaultValue>Char 2</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>Name for characteristic 2</Description>
            <ListPlacement>15</ListPlacement>
            <ArgPlacement>15</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_2_props</Name>
            <DataType>I</DataType>
            <DefaultValue>3</DefaultValue>
            <MinValue>0</MinValue>
            <MaxValue>15</MaxValue>
            <Description>Properties for char 2: 1=Read, 2=Write, 4=Notify, 8=Indicate (combine with +)</Description>
            <ListPlacement>16</ListPlacement>
            <ArgPlacement>16</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_2_max_len</Name>
            <DataType>I</DataType>
            <DefaultValue>20</DefaultValue>
            <MinValue>1</MinValue>
            <MaxValue>512</MaxValue>
            <Description>Maximum data length for characteristic 2</Description>
            <ListPlacement>17</ListPlacement>
            <ArgPlacement>17</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_3_uuid</Name>
            <DataType>S</DataType>
            <DefaultValue>00002A03-0000-1000-8000-00805F9B34FB</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>UUID for characteristic 3</Description>
            <ListPlacement>18</ListPlacement>
            <ArgPlacement>18</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_3_name</Name>
            <DataType>S</DataType>
            <DefaultValue>Char 3</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>Name for characteristic 3</Description>
            <ListPlacement>19</ListPlacement>
            <ArgPlacement>19</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_3_props</Name>
            <DataType>I</DataType>
            <DefaultValue>3</DefaultValue>
            <MinValue>0</MinValue>
            <MaxValue>15</MaxValue>
            <Description>Properties for char 3: 1=Read, 2=Write, 4=Notify, 8=Indicate (combine with +)</Description>
            <ListPlacement>20</ListPlacement>
            <ArgPlacement>20</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>char_3_max_len</Name>
            <DataType>I</DataType>
            <DefaultValue>20</DefaultValue>
            <MinValue>1</MinValue>
            <MaxValue>512</MaxValue>
            <Description>Maximum data length for characteristic 3</Description>
            <ListPlacement>21</ListPlacement>
            <ArgPlacement>21</ArgPlacement>
        </Parameter>
    </Parameters>
    <Functions>
        <Function>
            <name>init</name>
            <ID>
                <ERT1_ID>1</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>start_adv</name>
            <ID>
                <ERT1_ID>2</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>stop_adv</name>
            <ID>
                <ERT1_ID>3</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>write_char</name>
            <ID>
                <ERT1_ID>4</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>read_char</name>
            <ID>
                <ERT1_ID>5</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>notify_char</name>
            <ID>
                <ERT1_ID>6</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>on_client_write</name>
            <ID>
                <ERT1_ID>7</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>on_connect</name>
            <ID>
                <ERT1_ID>8</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>on_disconnect</name>
            <ID>
                <ERT1_ID>9</ERT1_ID>
            </ID>
        </Function>
    </Functions>
    <Ports>
        <Port>
            <Description>init</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>20</YCoordinate>
            <CName>init</CName>
            <Function argument="0">
                <Function_ERT1_ID>1</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>status</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>40</YCoordinate>
            <CName>status</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>init_done</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>20</YCoordinate>
            <Wcet>0</Wcet>
            <CName>init_done</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>init_error</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>30</YCoordinate>
            <Wcet>0</Wcet>
            <CName>init_error</CName>
            <Function argument="2">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>start_adv</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>57</YCoordinate>
            <CName>start_adv</CName>
            <Function argument="0">
                <Function_ERT1_ID>2</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <Description>adv_started</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>57</YCoordinate>
            <Wcet>0</Wcet>
            <CName>adv_started</CName>
            <Function argument="1">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>adv_error</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>67</YCoordinate>
            <Wcet>0</Wcet>
            <CName>adv_error</CName>
            <Function argument="2">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>stop_adv</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>85</YCoordinate>
            <CName>stop_adv</CName>
            <Function argument="0">
                <Function_ERT1_ID>3</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <Description>adv_stopped</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>85</YCoordinate>
            <Wcet>0</Wcet>
            <CName>adv_stopped</CName>
            <Function argument="1">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>write</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>105</YCoordinate>
            <CName>write</CName>
            <Function argument="0">
                <Function_ERT1_ID>4</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>char_idx</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>115</YCoordinate>
            <CName>char_idx</CName>
            <Function argument="1">
                <Function_ERT1_ID>4</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>data</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>125</YCoordinate>
            <CName>data</CName>
            <Function argument="2">
                <Function_ERT1_ID>4</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>length</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>135</YCoordinate>
            <CName>length</CName>
            <Function argument="3">
                <Function_ERT1_ID>4</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>write_status</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>115</YCoordinate>
            <CName>write_status</CName>
            <Function argument="1">
                <Function_ERT1_ID>4</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>write_done</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>105</YCoordinate>
            <Wcet>0</Wcet>
            <CName>write_done</CName>
            <Function argument="1">
                <Function_ERT1_ID>4</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>write_error</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>125</YCoordinate>
            <Wcet>0</Wcet>
            <CName>write_error</CName>
            <Function argument="2">
                <Function_ERT1_ID>4</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>read</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>157</YCoordinate>
            <CName>read</CName>
            <Function argument="0">
                <Function_ERT1_ID>5</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>read_idx</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>167</YCoordinate>
            <CName>read_idx</CName>
            <Function argument="1">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>read_data</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>167</YCoordinate>
            <CName>read_data</CName>
            <Function argument="1">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>read_length</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>177</YCoordinate>
            <CName>read_length</CName>
            <Function argument="2">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>read_status</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>187</YCoordinate>
            <CName>read_status</CName>
            <Function argument="3">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>read_done</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>157</YCoordinate>
            <Wcet>0</Wcet>
            <CName>read_done</CName>
            <Function argument="1">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>read_error</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>197</YCoordinate>
            <Wcet>0</Wcet>
            <CName>read_error</CName>
            <Function argument="2">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>notify</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>217</YCoordinate>
            <CName>notify</CName>
            <Function argument="0">
                <Function_ERT1_ID>6</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>notify_idx</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>227</YCoordinate>
            <CName>notify_idx</CName>
            <Function argument="1">
                <Function_ERT1_ID>6</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>notify_data</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>237</YCoordinate>
            <CName>notify_data</CName>
            <Function argument="2">
                <Function_ERT1_ID>6</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>notify_len</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>247</YCoordinate>
            <CName>notify_len</CName>
            <Function argument="3">
                <Function_ERT1_ID>6</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>notify_status</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>227</YCoordinate>
            <CName>notify_status</CName>
            <Function argument="1">
                <Function_ERT1_ID>6</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>notify_sent</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>217</YCoordinate>
            <Wcet>0</Wcet>
            <CName>notify_sent</CName>
            <Function argument="1">
                <Function_ERT1_ID>6</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>notify_error</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>237</YCoordinate>
            <Wcet>0</Wcet>
            <CName>notify_error</CName>
            <Function argument="2">
                <Function_ERT1_ID>6</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>client_wrote</Description>
            <PortType>InternalPort</PortType>
            <XCoordinate>-1</XCoordinate>
            <YCoordinate>-1</YCoordinate>
            <CName>client_wrote</CName>
            <Function argument="0">
                <Function_ERT1_ID>7</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>wrote_idx</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>275</YCoordinate>
            <CName>wrote_idx</CName>
            <Function argument="1">
                <Function_ERT1_ID>7</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>wrote_data</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>285</YCoordinate>
            <CName>wrote_data</CName>
            <Function argument="2">
                <Function_ERT1_ID>7</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>wrote_len</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>295</YCoordinate>
            <CName>wrote_len</CName>
            <Function argument="3">
                <Function_ERT1_ID>7</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>client_wrote_evt</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>265</YCoordinate>
            <Wcet>0</Wcet>
            <CName>client_wrote_evt</CName>
            <Function argument="1">
                <Function_ERT1_ID>7</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>connect</Description>
            <PortType>InternalPort</PortType>
            <XCoordinate>-1</XCoordinate>
            <YCoordinate>-1</YCoordinate>
            <CName>connect</CName>
            <Function argument="0">
                <Function_ERT1_ID>8</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>conn_handle</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>322</YCoordinate>
            <CName>conn_handle</CName>
            <Function argument="1">
                <Function_ERT1_ID>8</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>connect_evt</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>312</YCoordinate>
            <Wcet>0</Wcet>
            <CName>connect_evt</CName>
            <Function argument="1">
                <Function_ERT1_ID>8</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>disconnect</Description>
            <PortType>InternalPort</PortType>
            <XCoordinate>-1</XCoordinate>
            <YCoordinate>-1</YCoordinate>
            <CName>disconnect</CName>
            <Function argument="0">
                <Function_ERT1_ID>9</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>disc_handle</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>350</YCoordinate>
            <CName>disc_handle</CName>
            <Function argument="1">
                <Function_ERT1_ID>9</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>disc_reason</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>360</YCoordinate>
            <CName>disc_reason</CName>
            <Function argument="2">
                <Function_ERT1_ID>9</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>disconnect_evt</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>125</XCoordinate>
            <YCoordinate>340</YCoordinate>
            <Wcet>0</Wcet>
            <CName>disconnect_evt</CName>
            <Function argument="1">
                <Function_ERT1_ID>9</Function_ERT1_ID>
            </Function>
        </Port>
    </Ports>
</Component>
