<?xml version="1.0" encoding="UTF-8"?><Component>
    <Module>usercomponents</Module>
    <CDFInfo>
        <Version>3</Version>
        <CreationDate>2024-05-15T09:29:40Z</CreationDate>
        <UpdatedDate>2024-05-15T11:16:00Z</UpdatedDate>
    </CDFInfo>
    <Description>
        <ShortDescription>DAC</ShortDescription>
        <LongDescription>Digital-to-Analog Converter</LongDescription>
        <UserName/>
        <Menu>
            Peripherals
            <Menu>DAC</Menu>
        </Menu>
    </Description>
    <Block>
        <Type>IO</Type>
        <Height>50</Height>
        <Text>DAC</Text>
        <TextX>25</TextX>
        <TextY>5</TextY>
        <TextScale>1.25</TextScale>
        <TextVertical>0</TextVertical>
        <LocationX>0</LocationX>
        <LocationY>-10</LocationY>
    </Block>
    <FBID>
        <ERT1_ID>1</ERT1_ID>
        <Class>dac</Class>
    </FBID>
    <Hashes>
        <NameHash_CRC16>0x6628</NameHash_CRC16>
        <FbApiDescriptorHash_CRC32>59a727ef</FbApiDescriptorHash_CRC32>
        <FbApiDescriptorHash/>
    </Hashes>
    <Parameters>
        <Parameter>
            <Name>channel</Name>
            <DataType>I</DataType>
            <DefaultValue>0</DefaultValue>
            <MinValue>0</MinValue>
            <MaxValue>100</MaxValue>
            <Description>The channel of the DAC</Description>
            <ListPlacement>1</ListPlacement>
            <ArgPlacement>1</ArgPlacement>
            <DisplayOnWidget>
                <x>25</x>
                <y>25</y>
            </DisplayOnWidget>
        </Parameter>
        <Parameter>
            <Name>max</Name>
            <DataType>I</DataType>
            <DefaultValue>10000</DefaultValue>
            <MinValue>1</MinValue>
            <MaxValue>2147483647</MaxValue>
            <Description>The maximum value of the value input port</Description>
            <ListPlacement>2</ListPlacement>
            <ArgPlacement>2</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>sample rate</Name>
            <DataType>I</DataType>
            <DefaultValue>1000000</DefaultValue>
            <MinValue>1</MinValue>
            <MaxValue>2147483647</MaxValue>
            <Description>The sampling rate when DAC is a PWM, PDM or SDM modulator with low-pass filter</Description>
            <ListPlacement>3</ListPlacement>
            <ArgPlacement>3</ArgPlacement>
        </Parameter>
    </Parameters>
    <Functions>
        <Function>
            <name>set</name>
            <ID>
                <ERT1_ID>1</ERT1_ID>
            </ID>
        </Function>
    </Functions>
    <Ports>
        <Port>
            <Description>set</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>12</YCoordinate>
            <CName>set</CName>
            <Function argument="0">
                <Function_ERT1_ID>1</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>value</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>25</YCoordinate>
            <CName>value</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>--</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>80</XCoordinate>
            <YCoordinate>12</YCoordinate>
            <Wcet>0</Wcet>
            <CName>done</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
    </Ports>
</Component>
