<?xml version="1.0" encoding="UTF-8"?><Component>
    <ID>
        <ERT1_ID>2</ERT1_ID>
    </ID>
    <Class>json_stream_parser</Class>
    <FbApiDescriptorHash>todo Api Descriptor</FbApiDescriptorHash>
    <Hashes>
        <NameHash_CRC16>0xDCB6</NameHash_CRC16>
        <FbApiDescriptorHash_CRC16>todo Api Descriptor hash</FbApiDescriptorHash_CRC16>
    </Hashes>
    <Module>usercomponents</Module>
    <Menu>
        Data Utilities
        <Menu>
            JSON
            <Menu>JSON Stream Parser</Menu>
        </Menu>
    </Menu>
    <ShortDescription>JSON Stream Parser</ShortDescription>
    <LongDescription>Processes a text stream and generates events related to JSON parsing.</LongDescription>
    <Functions>
        <Function>
            <name>bob</name>
            <ID>
                <ERT1_ID>0</ERT1_ID>
            </ID>
        </Function>
    </Functions>
    <Port>
        <DataType>S</DataType>
        <CName>data</CName>
        <Description>data</Description>
        <PortType>InputPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>20</YCoordinate>
    </Port>
    <Port>
        <DataType>S</DataType>
        <CName>__</CName>
        <Description>--</Description>
        <PortType>OutputPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>20</YCoordinate>
    </Port>
    <Port>
        <CName>next</CName>
        <Description>next</Description>
        <PortType>StartPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>40</YCoordinate>
        <AtomicFlag>1</AtomicFlag>
    </Port>
    <Port>
        <CName>__</CName>
        <Description>--</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>40</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <CName>eos</CName>
        <Description>eos</Description>
        <PortType>StartPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>210</YCoordinate>
        <AtomicFlag>1</AtomicFlag>
    </Port>
    <Port>
        <CName>__</CName>
        <Description>--</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>210</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <CName>startMap</CName>
        <Description>startMap</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>50</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <CName>endMap</CName>
        <Description>endMap</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>60</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <CName>mapKey</CName>
        <Description>mapKey</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>100</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <DataType>I</DataType>
        <CName>DataType</CName>
        <Description>DataType</Description>
        <PortType>OutputPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>150</YCoordinate>
    </Port>
    <Port>
        <DataType>S</DataType>
        <CName>Data</CName>
        <Description>Data</Description>
        <PortType>OutputPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>160</YCoordinate>
    </Port>
    <Port>
        <DataType>S</DataType>
        <CName>Key</CName>
        <Description>Key</Description>
        <PortType>OutputPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>110</YCoordinate>
    </Port>
    <Port>
        <DataType>S</DataType>
        <CName>Parent</CName>
        <Description>Parent</Description>
        <PortType>OutputPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>120</YCoordinate>
    </Port>
    <Port>
        <CName>startArray</CName>
        <Description>startArray</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>70</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <CName>endArray</CName>
        <Description>endArray</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>80</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <CName>value</CName>
        <Description>value</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>140</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <CName>Error</CName>
        <Description>Error</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>180</YCoordinate>
        <Wcet>0</Wcet>
    </Port>
    <Port>
        <DataType>I</DataType>
        <CName>__</CName>
        <Description>--</Description>
        <PortType>OutputPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>190</YCoordinate>
    </Port>
    <Port>
        <CName>Readin</CName>
        <Description>Read</Description>
        <PortType>StartPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>10</YCoordinate>
        <AtomicFlag>1</AtomicFlag>
        <Function argument="0">
            <Function_ERT1_ID>0</Function_ERT1_ID>
        </Function>
    </Port>
    <Port>
        <CName>Readout</CName>
        <Description>Read</Description>
        <PortType>FinishPort</PortType>
        <XCoordinate>0</XCoordinate>
        <YCoordinate>10</YCoordinate>
        <Wcet>0</Wcet>
        <Function argument="1">
            <Function_ERT1_ID>0</Function_ERT1_ID>
        </Function>
    </Port>
</Component>
