<?xml version="1.0" encoding="UTF-8"?><Component>
    <Module>usercomponents</Module>
    <CDFInfo>
        <Version>3</Version>
        <CreationDate>2023-06-13T14:43:25Z</CreationDate>
        <UpdatedDate>2023-06-21T12:11:47Z</UpdatedDate>
    </CDFInfo>
    <Description>
        <ShortDescription>OTAA LoRaWAN module</ShortDescription>
        <LongDescription>This function block describes the LoRaWAN communication with external LoRaWAN module. The communication between the platform and this module is UART. The UART port on the platform is hardware to the first instance (e.g. UART0). The authentication mode is OTAA mode only. This is Class C (continuous) LoRaWAN communication only.</LongDescription>
        <UserName/>
        <Menu>
            Networking
            <Menu>LoraWAN</Menu>
        </Menu>
    </Description>
    <FBID>
        <ERT1_ID>1</ERT1_ID>
        <Class>lorawan</Class>
    </FBID>
    <Hashes>
        <NameHash_CRC16>0xC89A</NameHash_CRC16>
        <FbApiDescriptorHash_CRC32>bd595c67</FbApiDescriptorHash_CRC32>
        <FbApiDescriptorHash/>
    </Hashes>
    <Parameters>
        <Parameter>
            <Name>Target</Name>
            <DataType>I</DataType>
            <DefaultValue>0</DefaultValue>
            <MinValue>0</MinValue>
            <MaxValue>0</MaxValue>
            <Description>The LoRaWAN target module. Default to 0 (WIO-E5). 0 for Wio-E5.</Description>
            <ListPlacement>1</ListPlacement>
            <ArgPlacement>1</ArgPlacement>
            <DisplayOnWidget>
                <x>50</x>
                <y>5</y>
            </DisplayOnWidget>
        </Parameter>
        <Parameter>
            <Name>Mode</Name>
            <DataType>B</DataType>
            <DefaultValue>0</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>The connection mode of LoRaWAN. 0 for OTAA, 1 for ABP. Default to 0 (OTAA)</Description>
            <ListPlacement>2</ListPlacement>
            <ArgPlacement>2</ArgPlacement>
            <DisplayOnWidget>
                <x>50</x>
                <y>20</y>
            </DisplayOnWidget>
        </Parameter>
        <Parameter>
            <Name>Region</Name>
            <DataType>S</DataType>
            <DefaultValue>EU868</DefaultValue>
            <MinValue/>
            <MaxValue/>
            <Description>Region Parameters of LoRaWAN communications. Default to "EU868". The options are: "EU868", "US915", "CN779", "EU433", "AU915", "CN470", "AS923", "KR920", "IN865", "RU864", "STE920".</Description>
            <ListPlacement>3</ListPlacement>
            <ArgPlacement>3</ArgPlacement>
            <DisplayOnWidget>
                <x>50</x>
                <y>35</y>
            </DisplayOnWidget>
        </Parameter>
        <Parameter>
            <Name>REPT</Name>
            <DataType>I</DataType>
            <DefaultValue>1</DefaultValue>
            <MinValue>1</MinValue>
            <MaxValue>15</MaxValue>
            <Description>Unconfirmed message repeat time. From 1 to 15.</Description>
            <ListPlacement>4</ListPlacement>
            <ArgPlacement>4</ArgPlacement>
        </Parameter>
        <Parameter>
            <Name>RETRY</Name>
            <DataType>I</DataType>
            <DefaultValue>3</DefaultValue>
            <MinValue>0</MinValue>
            <MaxValue>254</MaxValue>
            <Description>Confirmed message retry times. From 0 to 254.</Description>
            <ListPlacement>5</ListPlacement>
            <ArgPlacement>5</ArgPlacement>
        </Parameter>
    </Parameters>
    <Functions>
        <Function>
            <name>connect</name>
            <ID>
                <ERT1_ID>1</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>on_receive_msg</name>
            <ID>
                <ERT1_ID>2</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>send_msg</name>
            <ID>
                <ERT1_ID>3</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>reset</name>
            <ID>
                <ERT1_ID>4</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>get_statusData</name>
            <ID>
                <ERT1_ID>5</ERT1_ID>
            </ID>
        </Function>
    </Functions>
    <Ports>
        <Port>
            <DataType>S</DataType>
            <Description>DevAddr</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>27</YCoordinate>
            <CName>DevAddr</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>AppKey</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>27</YCoordinate>
            <CName>AppKey</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>connect</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>15</YCoordinate>
            <CName>connect</CName>
            <Function argument="0">
                <Function_ERT1_ID>1</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>AppEui</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>40</YCoordinate>
            <CName>AppEui</CName>
            <Function argument="2">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>send_msg</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>122</YCoordinate>
            <CName>send_msg</CName>
            <Function argument="0">
                <Function_ERT1_ID>3</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>payload</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>147</YCoordinate>
            <CName>payload</CName>
            <Function argument="1">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>B</DataType>
            <Description>msg_confirmed</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>135</YCoordinate>
            <CName>msg_confirmed</CName>
            <Function argument="2">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>received</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>90</YCoordinate>
            <Wcet>0</Wcet>
            <CName>received</CName>
            <Function argument="1">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>recv_msg</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>102</YCoordinate>
            <CName>recv_msg</CName>
            <Function argument="1">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>reset</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>170</YCoordinate>
            <CName>reset</CName>
            <Function argument="0">
                <Function_ERT1_ID>4</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <Description>reset_done</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>170</YCoordinate>
            <Wcet>0</Wcet>
            <CName>reset_done</CName>
            <Function argument="1">
                <Function_ERT1_ID>4</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>get_data</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>192</YCoordinate>
            <CName>get_data</CName>
            <Function argument="0">
                <Function_ERT1_ID>5</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>status</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>205</YCoordinate>
            <CName>status</CName>
            <Function argument="1">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>send_errCode</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>147</YCoordinate>
            <CName>send_errCode</CName>
            <Function argument="1">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>DevEui</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>217</YCoordinate>
            <CName>DevEui</CName>
            <Function argument="2">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>fail</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>40</YCoordinate>
            <Wcet>0</Wcet>
            <CName>connectFail</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>ok</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>15</YCoordinate>
            <Wcet>0</Wcet>
            <CName>connectDone</CName>
            <Function argument="2">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>fail</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>135</YCoordinate>
            <Wcet>0</Wcet>
            <CName>send_fail</CName>
            <Function argument="1">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>ok</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>122</YCoordinate>
            <Wcet>0</Wcet>
            <CName>send_done</CName>
            <Function argument="2">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>ok</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>145</XCoordinate>
            <YCoordinate>192</YCoordinate>
            <Wcet>0</Wcet>
            <CName>data_got</CName>
            <Function argument="1">
                <Function_ERT1_ID>5</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>AppSKey</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>65</YCoordinate>
            <CName>AppSKey</CName>
            <Function argument="3">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>NwkSKey</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>77</YCoordinate>
            <CName>NwkSKey</CName>
            <Function argument="4">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>DevAddr_ABP</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>52</YCoordinate>
            <CName>DevAddr_ABP</CName>
            <Function argument="5">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
    </Ports>
</Component>
