<?xml version="1.0" encoding="UTF-8"?><Component>
    <Module>usercomponents</Module>
    <CDFInfo>
        <Version>3</Version>
        <CreationDate>2023-12-28T16:10:19Z</CreationDate>
        <UpdatedDate>2024-06-10T23:48:14Z</UpdatedDate>
    </CDFInfo>
    <Description>
        <ShortDescription>This function will retrieve data from the schedule information stored on a device.</ShortDescription>
        <LongDescription>This function will retrieve data from the schedule information stored on a device. 
This will be based on the NXP binary format for now, but doesn’t need to be specific to this.
</LongDescription>
        <UserName/>
        <Menu>
            Control Systems
            <Menu>Devman Scheduler</Menu>
        </Menu>
    </Description>
    <Block>
        <Type>Data</Type>
        <Height>150</Height>
        <Text>Scheduler</Text>
        <TextX>10</TextX>
        <TextY>5</TextY>
        <TextScale>1.25</TextScale>
        <TextVertical>0</TextVertical>
        <LocationX>0</LocationX>
        <LocationY>-15</LocationY>
    </Block>
    <FBID>
        <ERT1_ID>1</ERT1_ID>
        <Class>DevmanScheduler</Class>
    </FBID>
    <Hashes>
        <NameHash_CRC16>0x142C</NameHash_CRC16>
        <FbApiDescriptorHash_CRC32>11eac0c2</FbApiDescriptorHash_CRC32>
        <FbApiDescriptorHash/>
    </Hashes>
    <Parameters>
        <Parameter>
            <Name>ChannelID</Name>
            <DataType>I</DataType>
            <DefaultValue/>
            <MinValue>0</MinValue>
            <MaxValue>9</MaxValue>
            <Description>The ID of the scheduler's channel</Description>
            <ListPlacement>1</ListPlacement>
            <ArgPlacement>1</ArgPlacement>
            <DisplayOnWidget>
                <x>20</x>
                <y>20</y>
            </DisplayOnWidget>
        </Parameter>
        <Parameter>
            <Name>AutoMode</Name>
            <DataType>B</DataType>
            <DefaultValue/>
            <MinValue/>
            <MaxValue/>
            <Description>Whether we want the time polled from a clock automatically</Description>
            <ListPlacement>2</ListPlacement>
            <ArgPlacement>2</ArgPlacement>
        </Parameter>
    </Parameters>
    <Functions>
        <Function>
            <name>init_schedule</name>
            <ID>
                <ERT1_ID>1</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>get_schedule</name>
            <ID>
                <ERT1_ID>2</ERT1_ID>
            </ID>
        </Function>
        <Function>
            <name>set_schedule</name>
            <ID>
                <ERT1_ID>3</ERT1_ID>
            </ID>
        </Function>
    </Functions>
    <Ports>
        <Port>
            <Description>init</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>12</YCoordinate>
            <CName>init</CName>
            <Function argument="0">
                <Function_ERT1_ID>1</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <Description>get</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>40</YCoordinate>
            <CName>get</CName>
            <Function argument="0">
                <Function_ERT1_ID>2</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>time</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>50</YCoordinate>
            <CName>timeOfDayInMinutes</CName>
            <Function argument="1">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>day</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>60</YCoordinate>
            <CName>dayOfWeek</CName>
            <Function argument="2">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>set</Description>
            <PortType>StartPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>107</YCoordinate>
            <CName>set_schedule</CName>
            <Function argument="0">
                <Function_ERT1_ID>3</Function_ERT1_ID>
                <AtomicFlag>0</AtomicFlag>
            </Function>
        </Port>
        <Port>
            <DataType>S</DataType>
            <Description>data</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>117</YCoordinate>
            <CName>binary_data</CName>
            <Function argument="1">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>size</Description>
            <PortType>InputPort</PortType>
            <XCoordinate>0</XCoordinate>
            <YCoordinate>127</YCoordinate>
            <CName>data_size</CName>
            <Function argument="2">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>value</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>70</YCoordinate>
            <CName>value</CName>
            <Function argument="1">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>----</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>12</YCoordinate>
            <Wcet>0</Wcet>
            <CName>init_done</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>crc</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>22</YCoordinate>
            <CName>crc</CName>
            <Function argument="1">
                <Function_ERT1_ID>1</Function_ERT1_ID>
            </Function>
            <Function argument="1">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>----</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>40</YCoordinate>
            <Wcet>0</Wcet>
            <CName>OK</CName>
            <Function argument="1">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>error</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>50</YCoordinate>
            <Wcet>0</Wcet>
            <CName>error</CName>
            <Function argument="2">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>errno</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>60</YCoordinate>
            <CName>errno</CName>
            <Function argument="2">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>B</DataType>
            <Description>on</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>80</YCoordinate>
            <CName>is_on</CName>
            <Function argument="3">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>B</DataType>
            <Description>changed</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>90</YCoordinate>
            <CName>changed</CName>
            <Function argument="4">
                <Function_ERT1_ID>2</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>----</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>107</YCoordinate>
            <Wcet>0</Wcet>
            <CName>set_OK</CName>
            <Function argument="1">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <Description>error</Description>
            <PortType>FinishPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>117</YCoordinate>
            <Wcet>0</Wcet>
            <CName>error_set</CName>
            <Function argument="2">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
        <Port>
            <DataType>I</DataType>
            <Description>errno</Description>
            <PortType>OutputPort</PortType>
            <XCoordinate>65</XCoordinate>
            <YCoordinate>127</YCoordinate>
            <CName>set_errono</CName>
            <Function argument="2">
                <Function_ERT1_ID>3</Function_ERT1_ID>
            </Function>
        </Port>
    </Ports>
</Component>
