<?xml version="1.0" encoding="UTF-8"?><Component>
    <Module>usercomponents</Module>
    <ISNoCode>true</ISNoCode>
    <CDFInfo>
        <Version>3</Version>
        <CreationDate>2023-04-18T13:32:36Z</CreationDate>
        <UpdatedDate>2023-05-04T12:47:01Z</UpdatedDate>
    </CDFInfo>
    <Description>
        <ShortDescription/>
        <LongDescription/>
        <UserName/>
        <Menu>
            Software Structure
            <Menu>
                State Machine
                <Menu>State</Menu>
            </Menu>
        </Menu>
    </Description>
    <Block>
        <Type>State</Type>
        <Width>60</Width>
        <Height>60</Height>
    </Block>
    <FBID>
        <ERT1_ID>1</ERT1_ID>
        <Class>state</Class>
    </FBID>
    <Hashes>
        <NameHash_CRC16>0xCEA8</NameHash_CRC16>
        <FbApiDescriptorHash_CRC32>c0d8d429</FbApiDescriptorHash_CRC32>
        <FbApiDescriptorHash/>
    </Hashes>
    <Parameters>
        <Parameter>
            <Name>Name</Name>
            <DataType>S</DataType>
            <DefaultValue>State</DefaultValue>
            <MinValue>0</MinValue>
            <MaxValue>0</MaxValue>
            <Description/>
            <ListPlacement>1</ListPlacement>
            <ArgPlacement>1</ArgPlacement>
            <DisplayOnWidget>
                <x>25</x>
                <y>30</y>
                <CenterOrigin>1</CenterOrigin>
                <Scale>1.2</Scale>
            </DisplayOnWidget>
        </Parameter>
        <Parameter>
            <Name>__stateId</Name>
            <DataType>I</DataType>
            <DefaultValue>-1</DefaultValue>
            <MinValue>-2147483648</MinValue>
            <MaxValue>2147483647</MaxValue>
            <Description/>
            <ListPlacement>2</ListPlacement>
            <ArgPlacement>2</ArgPlacement>
        </Parameter>
    </Parameters>
    <Functions/>
    <Ports/>
</Component>
