<?xml version="1.0" encoding="UTF-8"?><Component>
	<Module>usercomponents</Module>
	<CDFInfo>
		<Version>3</Version>
		<CreationDate>2023-04-18T13:32:37Z</CreationDate>
		<UpdatedDate>2023-04-18T13:32:37Z</UpdatedDate>
	</CDFInfo>
	<Description>
        <ShortDescription/>
        <LongDescription/>
        <UserName/>
		<Menu>
			Deprecated
			<Menu>
				DTV
				<Menu>List Programmes</Menu>
			</Menu>
		</Menu>
	</Description>
	<Block>
		<Type>IO</Type>
	</Block>
	<FBID>
		<ERT1_ID>0</ERT1_ID>
		<Class>DtvPvrList</Class>
	</FBID>
	<Hashes>
		<NameHash_CRC16>0xCE13</NameHash_CRC16>
		<FbApiDescriptorHash_CRC32>5174e116</FbApiDescriptorHash_CRC32>
        <FbApiDescriptorHash/>
	</Hashes>
    <Parameters/>
	<Functions>
		<Function>
			<name>run</name>
			<ID>
				<ERT1_ID>1</ERT1_ID>
			</ID>
		</Function>
	</Functions>
	<Ports>
		<Port>
            <Description/>
			<PortType>StartPort</PortType>
			<XCoordinate>0</XCoordinate>
			<YCoordinate>10</YCoordinate>
            <CName/>
			<Function argument="0">
				<Function_ERT1_ID>1</Function_ERT1_ID>
				<AtomicFlag>1</AtomicFlag>
			</Function>
		</Port>
		<Port>
            <Description/>
			<PortType>FinishPort</PortType>
			<XCoordinate>100</XCoordinate>
			<YCoordinate>10</YCoordinate>
			<Wcet>0</Wcet>
            <CName/>
			<Function argument="1">
				<Function_ERT1_ID>1</Function_ERT1_ID>
			</Function>
		</Port>
		<Port>
			<DataType>S</DataType>
			<Description>name</Description>
			<PortType>OutputPort</PortType>
			<XCoordinate>100</XCoordinate>
			<YCoordinate>20</YCoordinate>
			<CName>Name</CName>
			<Function argument="1">
				<Function_ERT1_ID>1</Function_ERT1_ID>
			</Function>
		</Port>
		<Port>
			<DataType>B</DataType>
			<Description>valid</Description>
			<PortType>OutputPort</PortType>
			<XCoordinate>100</XCoordinate>
			<YCoordinate>30</YCoordinate>
			<CName>Valid</CName>
			<Function argument="2">
				<Function_ERT1_ID>1</Function_ERT1_ID>
			</Function>
		</Port>
	</Ports>
</Component>
