name=eRT
version=1.0.0
author=inx limited
maintainer=p.drezet@inx-systems.com
sentence=A static library for interfacing Lucid tools with Ardurino devices.
paragraph=Precompiled eRT static library for Arduino.
category=Uncategorized
url=https://github.com/your-repo
architectures=mbed,mbed_rp2040,ArduinoCore-mbed,mbed_nano
depends=WiFiNINA,ArduinoMqttClient,Arduino_LSM6DS3
precompiled=true
ldflags=-leRT_Kernel -leRT
