#!/usr/bin/env python3
"""
sodl_to_header.py
=================
Turn an exported SODL application (t.sdl) into a C header the target can embed,
so a board with no live app-upload path still boots with a real application.

    sodl_to_header.py <t.sdl> <out.h> [--app NAME]

Emits the same shape `xxd -i -n ehs_default_sodl` does, because that is what
target/os-arch/zephyr-arm/target_file.c already consumes:

    static const unsigned char ehs_default_sodl[] = { ... };
    static const unsigned int  ehs_default_sodl_len = N;

WHY A SCRIPT RATHER THAN `xxd -i`
---------------------------------
Three reasons, all of which bit during bring-up:
  * `xxd` is not installed in the build Docker image, and adding a tool to a
    shared image to run one command is a poor trade.
  * `xxd -i` names the array after the FILE PATH, so it only produces
    `ehs_default_sodl` if you also pass -n and get it exactly right. A silent
    rename becomes an "undefined reference" at link time.
  * A generated header wants provenance in it - which app, which source file,
    how big - so that a device flashed months ago can be identified from its
    source tree. `xxd` emits none of that.

SODL FORMAT SANITY CHECK
------------------------
ERT1 (SODL v1) exports begin with the byte 0x02. ERT0 is a text format starting
'#V:'. The kernel rejects a v0 file with a bare "Wrong SODL format", which is a
confusing thing to debug on a board with no console, so the mismatch is caught
here at build time instead. Pass --allow-any-format to bypass.
"""

import argparse
import sys
from pathlib import Path

SODL_V1_MAGIC = 0x02
BYTES_PER_LINE = 12


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('sdl', type=Path, help='exported t.sdl to embed')
    ap.add_argument('out', type=Path, help='header file to write')
    ap.add_argument('--app', default='', help='application name, for the comment header')
    ap.add_argument('--symbol', default='ehs_default_sodl',
                    help='C identifier for the array (default: ehs_default_sodl)')
    ap.add_argument('--allow-any-format', action='store_true',
                    help='skip the ERT1 magic-byte check')
    args = ap.parse_args()

    if not args.sdl.is_file():
        sys.exit(f"ERROR: SODL not found: {args.sdl}")

    data = args.sdl.read_bytes()
    if not data:
        sys.exit(f"ERROR: SODL is empty: {args.sdl}")

    if not args.allow_any_format and data[0] != SODL_V1_MAGIC:
        hint = ("looks like an ERT0/SODL-v0 text export" if data[:3] == b'#V:'
                else f"first byte is 0x{data[0]:02x}, expected 0x02")
        sys.exit(
            f"ERROR: {args.sdl} is not an ERT1 (SODL v1) export - {hint}.\n"
            f"       Export the app as ERT1, or set ERT_SODL_VERSION to match.\n"
            f"       Embedding a v0 file makes the kernel report the unhelpful\n"
            f"       'Wrong SODL format' at boot with no indication why.")

    lines = [
        '/***************************************************************\n',
        ' * Copyright (C) 2026 inx limited, UK - All Rights Reserved\n',
        ' * LGPLv3 license - see https://www.gnu.org/licenses/lgpl-3.0.txt\n',
        ' ***************************************************************/\n',
        '/* AUTO-GENERATED by scripts/sodl_to_header.py - DO NOT EDIT.\n',
        f' *   application : {args.app or "(unnamed)"}\n',
        f' *   source      : {args.sdl}\n',
        f' *   size        : {len(data)} bytes\n',
        ' *\n',
        ' * Regenerated on every build from EHS_DEFAULT_APP. To change which app\n',
        ' * is embedded, set EHS_DEFAULT_APP in the platform config.mk - do not\n',
        ' * edit this file.\n',
        ' */\n',
        '#ifndef EHS_DEFAULT_SODL_GENERATED_H\n',
        '#define EHS_DEFAULT_SODL_GENERATED_H\n',
        f'static const char {args.symbol}_app[] = "{args.app or "(unnamed)"}";\n',
        f'static const unsigned char {args.symbol}[] = {{\n',
    ]

    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk) +
                     (',\n' if i + BYTES_PER_LINE < len(data) else '\n'))

    lines.append('};\n')
    lines.append(f'static const unsigned int {args.symbol}_len = {len(data)};\n')
    lines.append('#endif /* EHS_DEFAULT_SODL_GENERATED_H */\n')

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(''.join(lines))
    print(f"Embedded app '{args.app}' ({len(data)} bytes) -> {args.out}")


if __name__ == '__main__':
    main()
