name: inxware/linux_amd64-buildenv

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
jobs:

  build:

    runs-on: ubuntu:18.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file <target/platform/XXX/Dockerfile> --tag my-image-name:$(date +%s)
