name: build-esp32s3_freertos-xtensa-community

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Using_Pulled_container:

    runs-on: ubuntu-22.04
    container:
      image: inxware/esp32_ubuntu22.04-build-essential
    steps:
    - uses: actions/checkout@v4
      with:
        path: ert-components
    - name: Checkout ert build support repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
            toolchains/x86_64
            support_libs/target_libs/xtensa-esp32s3_freertos
        repository: inxware/ert-build-support
        path: ert-build-support
        ref: refs/heads/main
        lfs: true

    - name: Checkout ert-contrib-middleware
      uses: actions/checkout@v4
      with:
        repository: inxware/ert-contrib-middleware
        path: ert-contrib-middleware
        sparse-checkout: target_libs/xtensa-esp32s3_freertos-xtensa-esp32s3-elf-5.1
        ref: refs/heads/main
        lfs: true

    - name: Checkout apps
      uses: actions/checkout@v4
      with:
        repository: inxware/apps
        path: apps
        ref: refs/heads/RELEASE-PRODUCTION
        
    - name: configure
      run: |
           cd ert-components
           ./configure esp32s3_freertos-xtensa-base

    - name: make
      run: |
           cd ert-components
           pwd
           make -j 8
           
    - name: make targetenv
      run: |
           cd ert-components
           pwd
           make targetenv
           
    - name: make package
      run: |
           cd ert-components
           pwd
#          make targetenv_esp32
