name: inxware/linux_amd64-buildenv

on:
  push:
    branches:
      - main
#  workflow_call:
#   inputs:
#      username:
#        description: 'A username passed from the caller workflow'
#        default: 'john-doe'
#        required: false
#        type: string
jobs:
  linux_x86_gtk_gst:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@main
    - name: Login to DockerHub Registry
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} 
        
      run:  docker login -u DOCKER_USER -p DOCKER_PASSWORD
        
        
#    - uses: actions/checkout@main
    - name: "running into docker"
      run: | 
        docker build - < ./target/platform/linux_amd64/Dockerfile --tag linux_amd64_image
        echo "Docker building complete Now run Docker image" 
        docker run -d --name x86_gtk_gst_container x86_gtk_gst_image "linux_x86_gtk_gst"
        docker ps | grep "x86_gtk_gst_container"
        echo "Configured linux_x86_gtk_gst"
        
    - name: "Push created image to dockerhub repository"
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/inxwaretesting
        echo "Pushed Complete"
