name: build-test-linux_x86_64_clang_gtk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Using_Pulled_container:

    runs-on: ubuntu-22.04
     container:
    image: inxware/inx-debian10-clang10
    steps:
    - uses: actions/checkout@v3
      with:
        path: ert-components
    - name: configure
      run: |
           cd ert-components
           ./configure linux_x86_64_clang
    - name: make
      run: |
           cd ert-components
           pwd
           make -j 8
    - name: make targetenv
      run: |
           cd ert-components
           pwd
           make targetenv
    - name: make package
      run: |
           cd ert-components
           pwd
           make targetenv_deb
