name: inxware/linux_amd64-buildenv

on:
  push:
    branches:
      - main
#  workflow_call:
#   inputs:
#      username:
#        description: 'A username passed from the caller workflow'
#        default: 'john-doe'
#        required: false
#        type: string
jobs:
  linux_x86_gtk_gst:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@main
    - name: Login to DockerHub Registry        
      run:  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} 
        
        
#    - uses: actions/checkout@main
    - name: "running into docker"
      run: | 
        docker build - < ./target/platform/linux_amd64/Dockerfile --tag inxwaretesting
        echo "Configured inxwaretesting"
        
    - name: "Push created image to dockerhub repository"
      run: |
        docker push zuhaibasgher/inxwaretesting:latest
        echo "Pushed Complete"
