name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    container:
      image: inxware/ubuntu22.04-build-essential
      options: --user root
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
      with:
        path: ert-components
    - name: Checkout tools repo
      uses: actions/checkout@v3 
      with:
        repository: inxware/ert-build-support
        path: ert-build-support
        ref: refs/heads/main
    - name: Checkout contrib middleware repo
      uses: actions/checkout@v3
      with:
        repository: inxware/ert-contrib-middleware
        path: ert-contrib-middleware
        ref: refs/heads/main
    - name: configure 
      run: | 
         cd ert-components
         tree -L 4 ../../
         pwd
         ./configure linux_android_arm
    - name: make
      run: |
         cd ert-components
         pwd
         make -j 8
    - name: make targetenv
      run: |
         cd ert-components
         pwd
         make targetenv
    - name: make distcheck
      run: |
         cd ert-components
         pwd
         make targetenv_deb
