name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure linux_x86_gtk_gst
   - name: checkout ert components
     uses: actions/checkout@v3
     with:
       path: ert-components
   - name: Checkout tools repo
     uses: actions/checkout@v3
     with:
        repository: inxware/ert-build-support
        path: ert-build-support
        lfs: true
   - name: Checkout contrib middleware repo
     uses: actions/checkout@v3
     with:
        repository: inxware/ert-contrib-middleware
        path: ert-contrib-middleware
        lfs: true
    - name: make
      run: make -j 8
    - name: make check
      run: make targetenv
    - name: make distcheck
      run: make targetenv_deb
