name: linux_x86_gtk_gst CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux_x86_gtk_gst:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@main
    - name: "running into docker"
      run: | 
        docker build - < ./target/platform/linux_x86_gtk_gst/Dockerfile --tag x86_gtk_gst_image
        echo "Docker building complete Now run Docker image" 
        docker run x86_gtk_gst_image
