name: linux_x86_gtk_gst CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux_x86_gtk_gst:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
      with:
        path: ert-components
        run: | 
          echo "debug: check working okay"
          docker build /target/platform/linux_x86_gtk_gst/ --tag x86_gtk_gst_image
          docker run x86_gtk_gst_image
